[server]
enableCORS = false
enableXsrfProtection = false
headless = true

[theme]
base = "light"
primaryColor = "#1e4d2b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f7"
textColor = "#111827"
