[theme]
primaryColor = "#245a34"
backgroundColor = "#f9f9f7"
secondaryBackgroundColor = "#e5e1da"
textColor = "#1c1c1c"
font = "sans serif"

[server]
maxUploadSize = 200
maxMessageSize = 220
enableXsrfProtection = true

